# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Reed 
email: danreedx86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dan Reed is an iOS developer in San Francisco.
  Also a musician, a gifted cook, a college graduate, and a talented raconteur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danreed.codes" # the base hostname & protocol for your site
twitter_username: danreedx86
github_username:  dreed1

# Build settings
markdown: kramdown
